SELECT A.PROGRAM, B.REQUEST_ID, B.STATUS_CODE, B.LOGFILE_NAME, B.OUTFILE_NAME, b.request_date
  FROM APPS.FND_CONCURRENT_REQUESTS B, apps.fnd_conc_req_summary_v a
 WHERE B.STATUS_CODE = 'E'
   AND TRUNC(B.request_date) > TRUNC(SYSDATE - 1)
 ORDER BY B.REQUEST_ID DESC